FROM python:3.10
RUN pip install poetry

WORKDIR /code

COPY pyproject.toml .
COPY readme.md .

COPY web/ ./web
COPY static/ ./static
COPY humitifier/ ./humitifier

RUN poetry install -n --all-extras

COPY entrypoint/demo.py /code/app.py

CMD ["poetry", "run", "python", "/code/app.py"]