version: '3'
services:
  web:
    image: humitifier:dev
    ports:
      - "8000:8000"
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
    volumes:
      - {YOUR USER CONFIG MODULE}:/code/user_config
      - $SSH_AUTH_SOCK:/ssh-agent