[tool.poetry]
name = "humitifier"
version = "0.1.0"
description = "Tools andi nterfaces for displaying HUM-IT resources"
authors = ["Donatas Rasiukevicius <d.rasiukevicius@uu.nl>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.93.0"
aiosql = "^7.2"
httpx = "^0.23.3"


[tool.poetry.group.dev.dependencies]
mypy = "^1.1.1"
pytest = "^7.2.2"
black = "^23.1.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
