# Generated by Django 5.1.6 on 2025-02-18 13:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="artefactspec",
            name="_scan_options",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="scanspec",
            name="_default_scan_options",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="scanspec",
            name="artefact_groups",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=100), default=list, size=None
            ),
        ),
    ]
