# Generated by Django 5.1.6 on 2025-02-18 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scanning", "0002_alter_artefactspec__scan_options_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="artefactspec",
            old_name="scan_profile",
            new_name="scan_spec",
        ),
    ]
