# Generated by Django 5.2.17 on 2026-08-27 12:30

import django.contrib.postgres.fields
import django.db.models.deletion
import network.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hosts", "0029_seed_operating_systems"),
    ]

    operations = [
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("vlan", models.IntegerField()),
                (
                    "cidr_range",
                    models.CharField(
                        max_length=100, validators=[network.models._validate_cidr_range]
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IPInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip_address", models.GenericIPAddressField()),
                ("active", models.BooleanField(default=False)),
                ("ping_time", models.FloatField(blank=True, null=True)),
                (
                    "reverse_dns_entries",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=255),
                        blank=True,
                        null=True,
                        size=None,
                    ),
                ),
                ("port_status", models.JSONField(blank=True, null=True)),
                ("last_scanned", models.DateTimeField(blank=True, null=True)),
                (
                    "host",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hosts.host",
                    ),
                ),
                (
                    "network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="network.network",
                    ),
                ),
            ],
        ),
    ]
