# Generated by Django 5.2.17 on 2026-08-28 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ipinfo",
            old_name="last_scanned",
            new_name="last_indexed",
        ),
        migrations.AddField(
            model_name="ipinfo",
            name="last_index_scheduled",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
