# Generated by Django 5.2.17 on 2026-08-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0029_seed_operating_systems"),
        ("network", "0002_rename_last_scanned_ipinfo_last_indexed_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ipinfo",
            name="host",
        ),
        migrations.AddField(
            model_name="ipinfo",
            name="hosts_from_dns",
            field=models.ManyToManyField(
                related_name="ipinfo_from_dns", to="hosts.host"
            ),
        ),
        migrations.AddField(
            model_name="ipinfo",
            name="hosts_from_ip",
            field=models.ManyToManyField(
                related_name="ipinfo_from_ip", to="hosts.host"
            ),
        ),
    ]
