# Generated by Django 5.1.6 on 2025-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CostsScheme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("start_date", models.DateField()),
                (
                    "cpu",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price per CPU"
                    ),
                ),
                (
                    "memory",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price per 1Gb memory",
                    ),
                ),
                (
                    "storage",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price per 1Tb storage",
                    ),
                ),
                (
                    "linux",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Price for Linux"
                    ),
                ),
                (
                    "windows",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="Price for Windows",
                    ),
                ),
            ],
        ),
    ]
