# Generated by Django 5.1.6 on 2025-04-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="costsscheme",
            name="start_date",
        ),
    ]
