# Generated by Django 5.1.6 on 2025-04-25 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0002_remove_costsscheme_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsscheme",
            name="redundant_storage",
            field=models.BooleanField(default=False),
        ),
    ]
