# Generated by Django 5.1.6 on 2025-04-25 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0003_costsscheme_redundant_storage"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsscheme",
            name="management",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Management costs",
            ),
            preserve_default=False,
        ),
    ]
