# Generated by Django 5.2.9 on 2026-08-05 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0005_generatedreport"),
    ]

    operations = [
        migrations.AddField(
            model_name="costsscheme",
            name="platform",
            field=models.CharField(default="vmware", max_length=100),
        ),
    ]
