# Generated by Django 5.2.9 on 2026-08-05 12:51

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0006_costsscheme_platform"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="costs_schemes",
            field=models.ManyToManyField(to="reporting.costsscheme"),
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="customers",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), default=[], size=None
            ),
            preserve_default=False,
        ),
    ]
