# Generated by Django 5.2.9 on 2026-08-05 13:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reporting", "0007_generatedreport_costs_schemes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="generatedreport",
            name="end_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="generatedreport",
            name="start_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
