[tool.poetry]
name = "humitifier-server"
version = "0.1.0"
description = ""
authors = ["Mees, T.D. (Ty) <t.d.mees@uu.nl>"]

[tool.poetry.dependencies]
python = "^3.11"
django = "~5.1"
bpython = "^0.24"
django-braces = "^1.16.0"
djangorestframework = "^3.15.2"
django-filter = "^24.3"
markdown = "^3.7"
django-debug-toolbar = "^4.4.6"
django-simple-menu = "^2.1.3"


[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
psycopg2-binary = {version = "^2.9.10", optional = true}
faker = "^30.8.0"


[tool.poetry.group.production.dependencies]
psycopg2 = {version = "^2.9.10", optional = true}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
