# Generated by Django 5.1.6 on 2025-03-14 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("alerting", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert",
            name="scan",
        ),
    ]
