# Generated by Django 5.1.6 on 2025-04-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alerting", "0002_remove_alert_scan"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alertacknowledgment",
            name="persistent",
            field=models.BooleanField(
                default=False,
                help_text="If checked, this alert will persist after the original alert condition disappears, suppressing any alerts in perpetuity",
                verbose_name="Persistent acknowledgement",
            ),
        ),
    ]
