# Generated by Django 5.1.2 on 2024-11-04 15:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "departments",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=200), size=None
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="default_home",
            field=models.CharField(
                choices=[("dashboard", "Dashboard"), ("hosts", "Hosts")],
                default="hosts",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="is_local_account",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="wild_wasteland_mode",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="access_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="main.accessprofile",
            ),
        ),
    ]
