# Generated by Django 5.1.2 on 2024-11-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_accessprofile_user_default_home_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="access_profile",
        ),
        migrations.AddField(
            model_name="user",
            name="access_profiles",
            field=models.ManyToManyField(
                blank=True, related_name="users", to="main.accessprofile"
            ),
        ),
    ]
