# Generated by Django 5.1.2 on 2024-11-08 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_user_access_profile_user_access_profiles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="default_home",
            field=models.CharField(
                choices=[("dashboard", "Dashboard"), ("hosts", "Hosts")],
                default="hosts",
                help_text="The default page to redirect to after login.",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="wild_wasteland_mode",
            field=models.BooleanField(
                default=False,
                help_text="Enables easter eggs, non-default as it's less professional.",
            ),
        ),
    ]
