# Generated by Django 5.1.3 on 2025-01-09 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_accessprofile_data_sources"),
    ]

    operations = [
        migrations.RenameField(
            model_name="accessprofile",
            old_name="departments",
            new_name="customers",
        ),
    ]
