"""
Django settings for humitifier_server project.

Generated by 'django-admin startproject' using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import re
from urllib.parse import urlparse

from django.core.exceptions import ImproperlyConfigured
from rest_framework.reverse import reverse_lazy
from sentry_sdk import HttpTransport
from sentry_sdk.integrations.celery import CeleryIntegration

from .config import CONFIG as HUMITIFIER_CONFIG

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

HUMITIFIER_VERSION = "4.14.2"
HUMITIFIER_VERSION_NAME = ".. is not a monitoring solution, honest"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = HUMITIFIER_CONFIG.django.secret_key.get_secret_value()

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = HUMITIFIER_CONFIG.django.debug

ALLOWED_HOSTS = HUMITIFIER_CONFIG.django.allowed_hosts
INTERNAL_IPS = [
    "127.0.0.1",
]


ENABLE_WHITENOISE = HUMITIFIER_CONFIG.static_files.enable_whitenoise

# Application definition

INSTALLED_APPS = [
    # Local apps with overrides here
    "main",
    # Django
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "django.forms",
    # Third-party apps
    "rest_framework",
    "simple_menu",
    "drf_spectacular",
    "oauth2_provider",
    "django_celery_beat",
    "django_celery_results",
    # Local apps
    "hosts",
    "api",
    "scanning",
    "alerting",
    "reporting",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

if ENABLE_WHITENOISE:
    index_of_security_middleware = MIDDLEWARE.index(
        "django.middleware.security.SecurityMiddleware"
    )
    MIDDLEWARE.insert(
        index_of_security_middleware + 1,
        "whitenoise.middleware.WhiteNoiseMiddleware",
    )


if DEBUG:
    INSTALLED_APPS.append("debug_toolbar")
    MIDDLEWARE.append("debug_toolbar.middleware.DebugToolbarMiddleware")

ROOT_URLCONF = "humitifier_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "main.context_processors.layout_context",
            ],
        },
    },
]

FORM_RENDERER = "main.forms.CustomFormRenderer"

WSGI_APPLICATION = "humitifier_server.wsgi.application"

# Auth
AUTH_USER_MODEL = "main.User"

# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": HUMITIFIER_CONFIG.database.database_name,
        "USER": HUMITIFIER_CONFIG.database.username,
        "PASSWORD": HUMITIFIER_CONFIG.database.password.get_secret_value(),
        "HOST": HUMITIFIER_CONFIG.database.host,
        "PORT": HUMITIFIER_CONFIG.database.port,
    }
}

# Authentication

LOGIN_URL = reverse_lazy("main:login")
LOGIN_REDIRECT_URL = reverse_lazy("main:home")
LOGOUT_REDIRECT_URL = reverse_lazy("main:home")

## OpenID Connect

if HUMITIFIER_CONFIG.oidc and HUMITIFIER_CONFIG.oidc.enabled:
    try:
        index = INSTALLED_APPS.index("django.contrib.auth")
        INSTALLED_APPS.insert(index + 1, "mozilla_django_oidc")
    except ValueError:
        raise ImproperlyConfigured(
            "Cannot enable OIDC; django.contrib.auth is not enabled"
        )

    if HUMITIFIER_CONFIG.oidc.session_refresh:
        MIDDLEWARE.append("mozilla_django_oidc.middleware.SessionRefresh")

    AUTHENTICATION_BACKENDS = [
        "humitifier_server.oidc_backend.HumitifierOIDCAuthenticationBackend",
        "django.contrib.auth.backends.ModelBackend",
    ]

    OIDC_EXEMPT_URLS = [
        re.compile(r"^api/.*$"),
    ]

    OIDC_CREATE_USER = HUMITIFIER_CONFIG.oidc.auto_create_user
    OIDC_RP_SCOPES = HUMITIFIER_CONFIG.oidc.rp_scopes

    OIDC_RP_SIGN_ALGO = HUMITIFIER_CONFIG.oidc.rp_sign_algorithm

    OIDC_AUTH_REQUEST_EXTRA_PARAMS = {}

    if _acr_values := HUMITIFIER_CONFIG.oidc.rp_acr_values:
        OIDC_AUTH_REQUEST_EXTRA_PARAMS["acr_values"] = _acr_values

    if client_id := HUMITIFIER_CONFIG.oidc.rp_client_id:
        OIDC_RP_CLIENT_ID = client_id
    else:
        raise ImproperlyConfigured("OIDC_RP_CLIENT_ID is required")

    if client_secret := HUMITIFIER_CONFIG.oidc.rp_client_secret.get_secret_value():
        OIDC_RP_CLIENT_SECRET = client_secret
    else:
        raise ImproperlyConfigured("OIDC_RP_CLIENT_SECRET is required")

    if jwk_endpoint := HUMITIFIER_CONFIG.oidc.op_jwks_endpoint:
        OIDC_OP_JWKS_ENDPOINT = jwk_endpoint
    else:
        raise ImproperlyConfigured("OIDC_OP_JWKS_ENDPOINT is required")

    if auth_endpoint := HUMITIFIER_CONFIG.oidc.op_authorization_endpoint:
        OIDC_OP_AUTHORIZATION_ENDPOINT = auth_endpoint
    else:
        raise ImproperlyConfigured("OIDC_OP_AUTHORIZATION_ENDPOINT is required")

    if token_endpoint := HUMITIFIER_CONFIG.oidc.op_token_endpoint:
        OIDC_OP_TOKEN_ENDPOINT = token_endpoint
    else:
        raise ImproperlyConfigured("OIDC_OP_TOKEN_ENDPOINT is required")

    if user_endpoint := HUMITIFIER_CONFIG.oidc.op_userinfo_endpoint:
        OIDC_OP_USER_ENDPOINT = user_endpoint
    else:
        raise ImproperlyConfigured("OIDC_OP_USER_ENDPOINT is required")

# DRF

REST_FRAMEWORK = {
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "oauth2_provider.contrib.rest_framework.OAuth2Authentication",
    ),
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Humitifier API",
    "DESCRIPTION": "API for Humitifier, the Hum-IT CMDB",
    "VERSION": HUMITIFIER_VERSION,
    "SERVE_INCLUDE_SCHEMA": False,
    # OAuth2
    "OAUTH2_FLOWS": ["clientCredentials"],
    "OAUTH2_AUTHORIZATION_URL": reverse_lazy("api:authorize"),
    "OAUTH2_TOKEN_URL": reverse_lazy("api:token"),
    "OAUTH2_REFRESH_URL": reverse_lazy("api:token"),
    "OAUTH2_SCOPES": None,
    # OTHER SETTINGS
}

## OAuth2

OAUTH2_PROVIDER_APPLICATION_MODEL = "api.OAuth2Application"

OAUTH2_PROVIDER = {
    "SCOPES": {
        "read": "Read scope",
        "system": "System scope",
    },
    "SCOPES_BACKEND_CLASS": "api.scopes.OAuth2Scopes",
}

# Security

_https_enabled = HUMITIFIER_CONFIG.django.enable_https

X_FRAME_OPTIONS = "DENY"
SECURE_SSL_REDIRECT = _https_enabled
SECURE_REDIRECT_EXEMPT = [r"^api/upload_scans/$"]

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = _https_enabled
CSRF_COOKIE_SECURE = _https_enabled
# Needed to work in kubernetes, as the app may be behind a proxy/may not know it's
# own domain
SESSION_COOKIE_DOMAIN = HUMITIFIER_CONFIG.cookie.domain
CSRF_COOKIE_DOMAIN = HUMITIFIER_CONFIG.cookie.domain
SESSION_COOKIE_NAME = HUMITIFIER_CONFIG.cookie.session_name
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 60 * 60 * 12  # 12 hours

CSRF_TRUSTED_ORIGINS = [
    f"http{'s' if _https_enabled else ''}://{host}" for host in ALLOWED_HOSTS
]

# Logging

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": HUMITIFIER_CONFIG.django.log_level,
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": HUMITIFIER_CONFIG.django.log_level,
            "propagate": False,
        },
        "humitifier-server": {
            "handlers": ["console"],
            "level": HUMITIFIER_CONFIG.django.log_level,
            "propagate": False,
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Europe/Amsterdam"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Whitenoise

STATIC_ROOT = BASE_DIR / "static"

MEDIA_URL = "media/"
MEDIA_ROOT = HUMITIFIER_CONFIG.files.storage_path

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
    },
}
if ENABLE_WHITENOISE:
    STORAGES["staticfiles"] = {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    }


# Sentry

import sentry_sdk


def before_send(event, hint):
    if "request" in event and "url" in event["request"]:
        url_string = event["request"]["url"]
        parsed_url = urlparse(url_string)
        hostname = parsed_url.hostname

        if hostname not in ALLOWED_HOSTS:
            return None

    return event


if HUMITIFIER_CONFIG.sentry:
    SENTRY_INSECURE_DSN = HUMITIFIER_CONFIG.sentry.insecure_cert

    class CustomHttpTransport(HttpTransport):
        def _get_pool_options(self):
            # This should never be used in production, or even on any server
            # THis is ONLY for when you're (for some reason) running sentry locally!
            options = super()._get_pool_options()
            if SENTRY_INSECURE_DSN:
                options["cert_reqs"] = "CERT_NONE"

            return options

    sentry_sdk.init(
        dsn=HUMITIFIER_CONFIG.sentry.dsn,
        traces_sample_rate=1.0,
        profile_session_sample_rate=1.0,
        profile_lifecycle="trace",
        before_send=before_send,
        transport=CustomHttpTransport,
        release=HUMITIFIER_VERSION,
        integrations=[
            CeleryIntegration(
                monitor_beat_tasks=True,
            ),
        ],
    )

## Celery

### Broker
if _redis_dsn := HUMITIFIER_CONFIG.celery.redis_dsn:
    CELERY_BROKER_URL = str(_redis_dsn)
elif _rabbit_mq_url := HUMITIFIER_CONFIG.celery.rabbit_mq_url:
    CELERY_BROKER_URL = str(_rabbit_mq_url)
else:
    raise ImproperlyConfigured("No Celery broker configured")
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True

### Result backend
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = True
