services:
  scanner:
    build:
      context: ..
      dockerfile: humitifier-scanner/Dockerfile
    environment:
      - HUMITIFIER_SCANNER_CELERY__RABBIT_MQ_URL=amqp://guest:guest@rabbitmq:5672//
    volumes:
      - .local/config.toml:/etc/humitifier-scanner/config.toml
    networks:
      - humitifier

networks:
  humitifier:
    name: humitifier