# Generated by Django 5.1.2 on 2024-10-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="last_scan_cache",
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name="host",
            name="last_scan_date",
            field=models.DateTimeField(null=True),
        ),
    ]
