# Generated by Django 5.1.2 on 2024-10-23 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0002_alter_host_last_scan_cache_alter_host_last_scan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="scan",
            name="host",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="scans",
                to="hosts.host",
            ),
        ),
    ]
