# Generated by Django 5.1.2 on 2024-10-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0003_alter_scan_host"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="contact",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        last_scan_cache__HostMeta__contact="null",
                        then=models.Value(None),
                    ),
                    models.When(
                        last_scan_cache__HostMeta__contact=None, then=models.Value(None)
                    ),
                    default=models.F("last_scan_cache__HostMeta__contact"),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="department",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        last_scan_cache__HostMeta__department="null",
                        then=models.Value(None),
                    ),
                    models.When(
                        last_scan_cache__HostMeta__department=None,
                        then=models.Value(None),
                    ),
                    default=models.F("last_scan_cache__HostMeta__department"),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
