# Generated by Django 5.1.2 on 2024-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0006_alter_host_options_host_os"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="type",
            field=models.CharField(
                choices=[
                    ("Outdated OS", "Outdated Os"),
                    ("Has fact error", "Fact Error"),
                    ("Puppet agent disabled", "Disabled Puppet"),
                ],
                max_length=255,
            ),
        ),
    ]
