# Generated by Django 5.1.2 on 2024-11-06 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0008_host_archival_date_host_archived"),
    ]

    operations = [
        migrations.AlterField(
            model_name="host",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Registered"),
        ),
        migrations.AlterField(
            model_name="host",
            name="fqdn",
            field=models.CharField(max_length=255, verbose_name="Hostname"),
        ),
    ]
