# Generated by Django 5.1.3 on 2024-12-09 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0009_alter_host_created_at_alter_host_fqdn"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("api", "API Sync"), ("manual", "Manual entry")],
                        default="manual",
                        max_length=255,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="host",
            name="data_source",
            field=models.ForeignKey(
                help_text="The data source for this host",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hosts",
                to="hosts.datasource",
                verbose_name="Data source",
            ),
        ),
    ]
