# Generated by Django 5.1.3 on 2025-01-08 13:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0010_datasource_host_data_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, editable=True, null=True),
        ),
    ]
