# Generated by Django 5.1.3 on 2025-01-08 13:15
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    DataSource = apps.get_model("hosts", "DataSource")
    for row in DataSource.objects.all():
        row.identifier = uuid.uuid4()
        row.save(update_fields=["identifier"])


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0011_datasource_identifier"),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
