# Generated by Django 5.1.3 on 2025-01-08 13:15
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0012_auto_20250108_1415"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasource",
            name="identifier",
            field=models.UUIDField(default=uuid.uuid4, unique=True, null=False),
        ),
    ]
