# Generated by Django 5.1.3 on 2025-01-09 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0015_host_has_tofu_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="otap_stage",
            field=models.CharField(blank=True, null=True),
        ),
    ]
