# Generated by Django 5.1.6 on 2025-02-20 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0017_datasource_scan_scheduling"),
        ("scanning", "0004_alter_artefactspec_knockout"),
    ]

    operations = [
        migrations.AddField(
            model_name="datasource",
            name="default_scan_spec",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="datasources",
                to="scanning.scanspec",
            ),
        ),
        migrations.AddField(
            model_name="host",
            name="scan_spec_override",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="hosts",
                to="scanning.scanspec",
            ),
        ),
    ]
