# Generated by Django 5.1.6 on 2025-03-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0018_datasource_default_scan_spec_host_scan_spec_override"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="host",
            name="os",
        ),
        migrations.AddField(
            model_name="host",
            name="os",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        then=models.Value(None),
                        **{
                            "last_scan_cache__facts__generic.HostnameCtl__os": "null",
                        },
                    ),
                    models.When(
                        then=models.Value(None),
                        **{
                            "last_scan_cache__facts__generic.HostnameCtl__os": None,
                        },
                    ),
                    default=models.F("last_scan_cache__facts__generic.HostnameCtl__os"),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
