# Generated by Django 5.1.6 on 2025-03-04 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0019_alter_host_os"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="last_scan_scheduled",
            field=models.DateTimeField(null=True),
        ),
    ]
