# Generated by Django 5.1.6 on 2025-03-11 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0021_alter_host_last_scan_cache_alter_scan_data"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Alert",
        ),
    ]
