# Generated by Django 5.1.9 on 2025-06-13 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0022_delete_alert"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="billable",
            field=models.BooleanField(default=False),
        ),
    ]
