# Generated by Django 5.2.9 on 2025-12-10 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0024_hostofflineperiod"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="hypervisor",
            field=models.GeneratedField(
                db_persist=True,
                expression=models.Case(
                    models.When(
                        then=models.Value(None),
                        **{
                            "last_scan_cache__facts__generic.HostnameCtl__virtualization": "null",
                        },
                    ),
                    models.When(
                        then=models.Value(None),
                        **{
                            "last_scan_cache__facts__generic.HostnameCtl__virtualization": None,
                        },
                    ),
                    default=models.F(
                        "last_scan_cache__facts__generic.HostnameCtl__virtualization"
                    ),
                ),
                output_field=models.CharField(max_length=255),
            ),
        ),
    ]
