# Generated by Django 5.2.9 on 2026-03-17 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0026_savedsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="host",
            name="asset_tag",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
