# Generated by Django 5.2.9 on 2026-08-12 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hosts", "0027_host_asset_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Should match the OS name as reported by the scanner exactly.",
                        max_length=255,
                        unique=True,
                    ),
                ),
                (
                    "outdated",
                    models.BooleanField(
                        default=False,
                        help_text="Hosts running an outdated operating system will get an 'Outdated OS' alert.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Operating system",
                "verbose_name_plural": "Operating systems",
                "ordering": ["name"],
            },
        ),
    ]
