from .department import Department
from .end_date import EndDate
from .fqdn import Fqdn
from .hostname import Hostname
from .local_storage import LocalStorage
from .memory_use import MemoryUse
from .os import Os
from .owner import Owner
from .package_list import PackageList
from .purpose import Purpose
from .start_date import StartDate
from .virtualization import Virtualization