first_names = [
    "Harry",
    "Ron",
    "Hermione",
    "Ginny",
    "Fred",
    "George",
    "Percy",
    "Charlie",
    "Bill",
    "Arthur",
    "Molly",
    "Lily",
    "James",
    "Sirius",
    "Remus",
    "Severus",
    "Albus",
    "Minerva",
    "Rubeus",
    "Neville",
    "Luna",
    "Draco",
    "Crabbe",
    "Goyle",
    "Vincent",
    "Gregory",
    "Cedric",
    "Cho",
    "Fleur",
    "Victoire",
    "Dominique",
]

last_names = [
    "Potter",
    "Weasley",
    "Granger",
    "Malfoy",
    "Black",
    "Longbottom",
    "Lestrange",
    "Lovegood",
    "Diggory",
    "Crouch",
    "Flint",
    "Goyle",
    "Smith",
    "Bulstrode",
    "Crabbe",
    "Macmillan",
    "Nott",
    "Parkinson",
    "Zabini",
    "Baddock",
    "Rosier",
    "Selwyn",
    "Shacklebolt",
    "Travers",
    "Yaxley",
    "Avery",
    "Dolohov",
    "Gaunt",
    "LeStrange",
    "Ollivander",
    "Pettigrew",
]

domains = [
    "potions.com",
    "quidditch.net",
    "charms.org",
    "magicalcreatures.gov",
    "spellcasting.co.uk",
    "darkarts.org",
    "wizardingworld.com",
    "muggles.net",
    "wizardingschool.edu",
    "diagonalley.com",
]


departments = [
    "Charms",
    "Transfiguration",
    "Potions",
    "Herbology",
    "Defense Against the Dark Arts",
    "Divination",
    "History of Magic",
    "Magical Creatures",
    "Astronomy",
    "Muggle Studies",
]


packages = [
    "quidditch",
    "potion-maker",
    "spell-checker",
    "herbology",
    "transfiguration",
    "charms",
    "divination",
    "defense-against-the-dark-arts",
    "magical-creatures",
    "alchemy",
    "apparition",
    "astronomy",
    "enchantment",
    "flying",
    "history-of-magic",
    "muggle-studies",
    "runes",
    "study-of-ancient-runes",
    "care-of-magical-creatures",
    "arithmancy",
]

operating_systems = ["WizOS", "EnchantedOS", "SpellboundOS", "MagiX", "WizardryOS"]
applications = ["Web server", "Database server", "Email server", "FTP server", "DNS server"]
user_groups = ["students", "professors", "staff", "administrators", "guests"]
kernels = ["spells", "potions", "wandlore", "divination", "creatures"]
mountpoints = ["/mnt/disk1", "/mnt/disk2", "/mnt/disk3", "/mnt/disk4", "/mnt/disk5"]
block_devices = ["/dev/sda", "/dev/sdb", "/dev/sdc", "/dev/sdd", "/dev/sde"]
shells = ["/bin/bash", "/bin/zsh", "/bin/ksh", "/bin/csh", "/bin/tcsh"]
