# Generated by Django 5.1.2 on 2024-11-12 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        ("main", "0004_alter_user_default_home_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="oauth2application",
            name="access_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="oauth_applications",
                to="main.accessprofile",
            ),
        ),
    ]
