services:
  web:
    image: humitifier:dev
    environment:
      - SSH_AUTH_SOCK=/ssh-agent
      - HUMITIFIER_CONFIG=/code/app_config.toml
    volumes:
      - .local/app_config_compose.toml:/code/app_config.toml # Reference your configuration
      - $SSH_AUTH_SOCK:/ssh-agent
    
  db:
    image: postgres:15
    expose:
      - 5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres