name: Build and Push Docker Images

on:
  push:
    tags:
      - '*'
  workflow_dispatch:

env:
  IMAGE_NAME: humitifier
  DOCKERFILE_DEMO_PATH: ./Dockerfile.demo
  DOCKERFILE_PATH: ./Dockerfile

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Compile CSS from SCSS files
        uses: gha-utilities/sass-build@v0.5.1
        with:
          source: web/style.scss
          destination: static/out.css

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push demo image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_DEMO_PATH }}
          push: true
          tags: ghcr.io/centrefordigitalhumanities/humitifier/${{ env.IMAGE_NAME }}:demo
      
      - name: Build and push main image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ${{ env.DOCKERFILE_PATH }}
          push: true
          tags: ghcr.io/centrefordigitalhumanities/humitifier/${{ env.IMAGE_NAME }}:latest